#' Simulate event counts with independent disparity and total intensity
#'
#' The disparity surface varies east-west and expected total events
#'   north-south.
#' Their lattice correlation is zero by construction. Counts are Poisson
#'   events,
#' then unknown ethnicity is generated by binomial thinning. MCAR has a common
#' probability, MAR varies by synthetic force, and MNAR varies by ethnicity.
#' True latent rate ratios and complete realised event ratios are distinct.
#' @param side Lattice width and height, at least three.
#' @param surface Smooth, discontinuous, or small comparison-population
#'   setting.
#' @param population Resident reference/comparison populations per area.
#' @param rate Mean total annual event rate per resident.
#' @param missingness Missing-ethnicity mechanism.
#' @param missing_rate Baseline missing probability.
#' @param months Number of submitted months, between one and twelve.
#' @param seed Reproducible seed, restored on exit.
#' @return A list of counts, complete_counts, population, boundaries,
#'   truth and
#'   settings. Counts carry a clearly synthetic ingestion contract.
#' @family inference
#' @seealso [sl_spatial_disparity()], [sl_missing_ethnicity_bounds()]
#' @export
#' @examples
#' s <- sl_simulate(side = 3, missingness = "mnar", missing_rate = 0.3)
#' s$truth
#' sl_missing_ethnicity_bounds(s$counts, s$population,
#'   scenarios = c("all_to_reference", "all_to_comparison")
#' )
sl_simulate <- function(side = 6,
                        surface = c("smooth", "discontinuous", "small"),
                        population = c(White = 5000, Black = 1000),
                        rate = 0.025,
                        missingness = c("none", "mcar", "mar", "mnar"),
                        missing_rate = 0.2, months = 12, seed = 1) {
  surface <- match.arg(surface)
  missingness <- match.arg(missingness)
  valid <- length(side) == 1L && is.finite(side) && side >= 3 &&
    side == floor(side) && length(months) == 1L && is.finite(months) &&
    months >= 1 && months <= 12 && months == floor(months) &&
    length(population) == 2L && all(is.finite(population) & population > 0) &&
    length(rate) == 1L && is.finite(rate) && rate > 0 &&
    length(missing_rate) == 1L && is.finite(missing_rate) &&
    missing_rate >= 0 && missing_rate <= 1
  if (!valid) {
    sl_abort("Invalid lattice, population, rate or missingness settings.")
  }
  if (surface == "small") population[2] <- population[2] / 20
  sl_with_seed(seed, {
    xy <- expand.grid(x = seq_len(side), y = seq_len(side))
    code <- sprintf("SIM%04d", seq_len(nrow(xy)))
    east <- (xy$x - mean(xy$x)) / max(abs(xy$x - mean(xy$x)))
    north <- (xy$y - mean(xy$y)) / max(abs(xy$y - mean(xy$y)))
    contrast <- if (surface == "discontinuous") {
      ifelse(east < 0, -0.8, 0.8)
    } else {
      0.8 * east
    }
    ratio <- exp(log(2) + contrast)
    intensity <- sum(population) * rate * exp(0.6 * north)
    theta_ref <- intensity / (population[1] + population[2] * ratio)
    force <- ifelse(xy$x <= side / 2, "synthetic-west", "synthetic-east")
    polygons <- lapply(seq_len(nrow(xy)), function(i) {
      x <- 400000 + (xy$x[i] - 1) * 1000
      y <- 300000 + (xy$y[i] - 1) * 1000
      sf::st_polygon(list(rbind(
        c(x, y), c(x + 1000, y),
        c(x + 1000, y + 1000), c(x, y + 1000), c(x, y)
      )))
    })
    boundaries <- sf::st_sf(
      geography_code = code,
      geometry = sf::st_sfc(polygons, crs = 27700)
    )
    attr(boundaries, "geography_metadata") <- list(
      type = "synthetic",
      vintage = "synthetic lattice", crs = 27700
    )
    cells <- expand.grid(
      area = seq_along(code),
      month = sprintf("2026-%02d", seq_len(months)),
      ethnicity = c("White", "Black", "Unknown"), stringsAsFactors = FALSE
    )
    cells$geography_code <- code[cells$area]
    cells$force_id <- force[cells$area]
    cells$object_group <- "synthetic object"
    cells$status <- "submitted"
    cells$months_submitted <- 1L
    cells$n <- 0L
    known <- cells$ethnicity != "Unknown"
    comparison <- cells$ethnicity == "Black"
    mean_count <- theta_ref[cells$area] *
      ifelse(comparison, ratio[cells$area] * population[2], population[1]) / 12
    cells$n[known] <- stats::rpois(sum(known), mean_count[known])
    complete <- cells
    probability <- rep(missing_rate, nrow(cells))
    if (missingness == "none") probability[] <- 0
    if (missingness == "mar") {
      shift <- ifelse(cells$force_id == "synthetic-west", -1, 1)
      probability <- stats::plogis(stats::qlogis(missing_rate) + shift)
    }
    if (missingness == "mnar") {
      shift <- ifelse(comparison, 1, -1)
      probability <- stats::plogis(stats::qlogis(missing_rate) + shift)
    }
    lost <- stats::rbinom(nrow(cells), cells$n, probability)
    cells$n <- cells$n - lost
    totals <- tapply(lost, paste(cells$area, cells$month), sum)
    cells$n[!known] <- totals[paste(cells$area[!known], cells$month[!known])]
    contract <- sl_new_contract()
    contract$source <- "searchlight synthetic Poisson lattice"
    contract$analysis <- list(
      geography = "synthetic", classification = "5",
      scheme = "self-defined", strata = c("force_id", "geography_code")
    )
    contract$coverage <- unique(cells[c("force_id", "month", "status")])
    contract$geography <- list(
      synthetic =
        attr(boundaries, "geography_metadata")
    )
    contract$simulation <- list(
      seed = seed, surface = surface,
      missingness = missingness, missing_rate = missing_rate
    )
    p <- expand.grid(
      geography_code = code,
      ethnicity = c("White", "Black", "Unknown"), stringsAsFactors = FALSE
    )
    p$population <- rep(c(population, NA_real_), each = length(code))
    p <- sl_exposure(p, "synthetic", source = "Known synthetic population")
    contract$population <- sl_contract(p)$population
    counts <- sl_carry(tibble::as_tibble(cells), contract, "sl_counts")
    complete <- sl_carry(tibble::as_tibble(complete), contract, "sl_counts")
    truth <- tibble::tibble(
      geography_code = code, force_id = force,
      x = xy$x, y = xy$y, ratio = ratio, annual_intensity = intensity,
      rate_reference = theta_ref, rate_comparison = theta_ref * ratio
    )
    list(
      counts = counts, complete_counts = complete, population = p,
      boundaries = boundaries, truth = truth, settings = contract$simulation
    )
  })
}
