name: pkgdown
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown
          needs: website
      - name: Configure documentation commit identity
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
